services:

  db:
    image: postgres:15
    container_name: student-db
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    image: student-api:1.0.0
    container_name: student-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/students
      LOG_LEVEL: INFO
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  postgres_data: