namespace: student-api

image:
  repository: harshadabade/student-api
  tag: "c1e71d9a8d7991cb7cc6f81741d7e58037311c4f"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5000
  nodePort: 30050

nodeSelector:
  type: application

env:
  logLevel: "INFO"

database:
  host: "postgresql.student-api.svc.cluster.local"
  port: 5432
  name: "students"
  user: "postgres"