namespace: student-api

image:
  repository: harshadabade/student-api
  tag: "fdc68ab74fd17fcb6a59fd0f2bc3720f73fe17fd"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5000
  nodePort: 30050

nodeSelector:
  type: application

env:
  logLevel: "INFO"

database:
  host: "postgresql.student-api.svc.cluster.local"
  port: 5432
  name: "students"
  user: "postgres"