namespace: student-api

image:
  repository: harshadabade/student-api
  tag: "cadffd167032445582527d388b99b782aa9d3d34"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5000
  nodePort: 30050

nodeSelector:
  type: application

env:
  logLevel: "INFO"

database:
  host: "postgresql.student-api.svc.cluster.local"
  port: 5432
  name: "students"
  user: "postgres"