global:
  postgresql:
    auth:
      username: postgres
      database: students
      existingSecret: postgresql-secret
      secretKeys:
        userPasswordKey: postgres-password

primary:
  nodeSelector:
    type: database

  persistence:
    enabled: true
    size: 1Gi

volumePermissions:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: observability
    labels:
      release: kube-prometheus-stack

fullnameOverride: postgresql
