apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-external-secret
  namespace: student-api
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: student-api-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: student-api/db
        property: DATABASE_URL