apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-external-secret
  namespace: observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: alertmanager-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: webhook_url
      remoteRef:
        key: student-api/slack
        property: webhook_url
