config:
  clients:
    - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
      tenant_id: foo

  snippets:
    pipelineStages:
      - cri: {}
    scrapeConfigs: |
      - job_name: student-api-logs
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - cri: {}
          - match:
              selector: '{namespace!="student-api"}'
              action: drop
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            separator: /
            target_label: __path__
            replacement: /var/log/pods/*$1/*.log
          - source_labels: [__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash, __meta_kubernetes_pod_annotation_kubernetes_io_config_hash, __meta_kubernetes_pod_container_name]
            separator: /
            regex: true/(.*)
            target_label: __path__
            replacement: /var/log/pods/*$1/*.log
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service_name
