name: CI/CD Pipeline

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Dockerfile'
      - 'Makefile'
  workflow_dispatch:

jobs:
  build-test-lint-push:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.11.23/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build API (install dependencies)
        run: make install

      - name: Run tests
        run: make test

      - name: Run code linting
        run: make lint

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-api:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-api:${{ github.sha }}
  
      - name: Update Helm values with new image tag
        run: |
          sed -i '' "s|tag: .*|tag: \"${{ github.sha }}\"|" helm/application/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/application/values.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
